//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointOfSale.DAL.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية الفعلية.
        /// </summary>
        public static string ActualQuantity {
            get {
                return ResourceManager.GetString("ActualQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العنوان.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العنوان مطلوب.
        /// </summary>
        public static string AddressTypeRequired {
            get {
                return ResourceManager.GetString("AddressTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات الأسعار المتقدمة.
        /// </summary>
        public static string AdvancedPriceICollections {
            get {
                return ResourceManager.GetString("AdvancedPriceICollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظفين المتاحين .
        /// </summary>
        public static string AllowedEmployees {
            get {
                return ResourceManager.GetString("AllowedEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل المنتجات.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قدم الطلب.
        /// </summary>
        public static string ApplyOn {
            get {
                return ResourceManager.GetString("ApplyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفويض الاختلاف.
        /// </summary>
        public static string AuthorizedDifference {
            get {
                return ResourceManager.GetString("AuthorizedDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الايصالات تلقائى.
        /// </summary>
        public static string AutomaticReceiptPrinting {
            get {
                return ResourceManager.GetString("AutomaticReceiptPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات المتاحة.
        /// </summary>
        public static string AvailableCategories {
            get {
                return ResourceManager.GetString("AvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح فى نقاط البيع.
        /// </summary>
        public static string AvailableInPOS {
            get {
                return ResourceManager.GetString("AvailableInPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوائم الأسعار المتاحة.
        /// </summary>
        public static string AvailablePriceLists {
            get {
                return ResourceManager.GetString("AvailablePriceLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باركود.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسمية الباركود
        ///ت.
        /// </summary>
        public static string BarcodeNomenclature {
            get {
                return ResourceManager.GetString("BarcodeNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمط الباركود.
        /// </summary>
        public static string BarcodePattern {
            get {
                return ResourceManager.GetString("BarcodePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماسح الباركود.
        /// </summary>
        public static string BarcodeScanner {
            get {
                return ResourceManager.GetString("BarcodeScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الباركود.
        /// </summary>
        public static string BarcodeType {
            get {
                return ResourceManager.GetString("BarcodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الفاتورة.
        /// </summary>
        public static string BillPrinting {
            get {
                return ResourceManager.GetString("BillPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقسيم الفاتورة.
        /// </summary>
        public static string BillSpliitting {
            get {
                return ResourceManager.GetString("BillSpliitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشترى.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن صرفها.
        /// </summary>
        public static string CanBeExpensed {
            get {
                return ResourceManager.GetString("CanBeExpensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن شراءه.
        /// </summary>
        public static string CanBePurchased {
            get {
                return ResourceManager.GetString("CanBePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن تأجيرها.
        /// </summary>
        public static string CanBeRented {
            get {
                return ResourceManager.GetString("CanBeRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن بيعها.
        /// </summary>
        public static string CanBeSold {
            get {
                return ResourceManager.GetString("CanBeSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        public static string Cancled {
            get {
                return ResourceManager.GetString("Cancled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدى.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة النقد.
        /// </summary>
        public static string CashControl {
            get {
                return ResourceManager.GetString("CashControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعين صوره للفئة.
        /// </summary>
        public static string CategoryPictures {
            get {
                return ResourceManager.GetString("CategoryPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاغلاق.
        /// </summary>
        public static string ClosedDate {
            get {
                return ResourceManager.GetString("ClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string Colsed {
            get {
                return ResourceManager.GetString("Colsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان 1.
        /// </summary>
        public static string CompanyAddressStreet1 {
            get {
                return ResourceManager.GetString("CompanyAddressStreet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان 2.
        /// </summary>
        public static string CompanyAddressStreet2 {
            get {
                return ResourceManager.GetString("CompanyAddressStreet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توصيل الأجهزة.
        /// </summary>
        public static string ConnectDevices {
            get {
                return ResourceManager.GetString("ConnectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستهلك.
        /// </summary>
        public static string Consumable {
            get {
                return ResourceManager.GetString("Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة .
        /// </summary>
        public static string ContactImage {
            get {
                return ResourceManager.GetString("ContactImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الاتصال.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة التحكم.
        /// </summary>
        public static string ControlPolicy {
            get {
                return ResourceManager.GetString("ControlPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلقة بواسطة.
        /// </summary>
        public static string CosedBy {
            get {
                return ResourceManager.GetString("CosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الفروع.
        /// </summary>
        public static string CountOfBranches {
            get {
                return ResourceManager.GetString("CountOfBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الموظفين.
        /// </summary>
        public static string CountOfEmployees {
            get {
                return ResourceManager.GetString("CountOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة البلدان.
        /// </summary>
        public static string CountryGroup {
            get {
                return ResourceManager.GetString("CountryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مجموعه البلدان.
        /// </summary>
        public static string CountryGroupName {
            get {
                return ResourceManager.GetString("CountryGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدوله.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء مسودة أمر شراء.
        /// </summary>
        public static string CreateADraftPurchaseOrder {
            get {
                return ResourceManager.GetString("CreateADraftPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشئ بواسطة.
        /// </summary>
        public static string CreatedUserId {
            get {
                return ResourceManager.GetString("CreatedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريه الاضافة.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية الحالية.
        /// </summary>
        public static string CurrentQuantity {
            get {
                return ResourceManager.GetString("CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة العميل.
        /// </summary>
        public static string CustomerImage {
            get {
                return ResourceManager.GetString("CustomerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلة العميل.
        /// </summary>
        public static string CustomerLeadTime {
            get {
                return ResourceManager.GetString("CustomerLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل مطلوب.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضرائب العملاء.
        /// </summary>
        public static string CustomerTaxes {
            get {
                return ResourceManager.GetString("CustomerTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العميل.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العميل مطلوب.
        /// </summary>
        public static string CustomerTypeRequired {
            get {
                return ResourceManager.GetString("CustomerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الحذف.
        /// </summary>
        public static string DeleteDate {
            get {
                return ResourceManager.GetString("DeleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خذف بواسطة.
        /// </summary>
        public static string DeletedUserId {
            get {
                return ResourceManager.GetString("DeletedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكميات المسلمة.
        /// </summary>
        public static string DeliveredQuantities {
            get {
                return ResourceManager.GetString("DeliveredQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف لأوامر التسليم.
        /// </summary>
        public static string DescriptionForDeliveryOrders {
            get {
                return ResourceManager.GetString("DescriptionForDeliveryOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الإيصالات.
        /// </summary>
        public static string DescriptionForReceipts {
            get {
                return ResourceManager.GetString("DescriptionForReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف تلقائيا.
        /// </summary>
        public static string DetectAutomatically {
            get {
                return ResourceManager.GetString("DetectAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مدفوع.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التشفير.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طابعة إبسون.
        /// </summary>
        public static string Epsonprinter {
            get {
                return ResourceManager.GetString("Epsonprinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقف المالي.
        /// </summary>
        public static string Fiscalposition {
            get {
                return ResourceManager.GetString("Fiscalposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوظيفة المالية.
        /// </summary>
        public static string FiscalPositionName {
            get {
                return ResourceManager.GetString("FiscalPositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب مسبق للوضع المالي.
        /// </summary>
        public static string FiscalPositionPerOrder {
            get {
                return ResourceManager.GetString("FiscalPositionPerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدور.
        /// </summary>
        public static string FloorName {
            get {
                return ResourceManager.GetString("FloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادوار.
        /// </summary>
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طاولات الدور.
        /// </summary>
        public static string FloorsTables {
            get {
                return ResourceManager.GetString("FloorsTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسفل الايصال.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء باركود.
        /// </summary>
        public static string GenerateBarcode {
            get {
                return ResourceManager.GetString("GenerateBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم عام.
        /// </summary>
        public static string GlobalDiscounts {
            get {
                return ResourceManager.GetString("GlobalDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رأس الايصال.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة رأس و اسفل الايصال.
        /// </summary>
        public static string HeaderFooter {
            get {
                return ResourceManager.GetString("HeaderFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز النظام المنسق.
        /// </summary>
        public static string HSCode {
            get {
                return ResourceManager.GetString("HSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فردى.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقسيط.
        /// </summary>
        public static string Instalment {
            get {
                return ResourceManager.GetString("Instalment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرجع الداخلي.
        /// </summary>
        public static string InternalReference {
            get {
                return ResourceManager.GetString("InternalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفواتير.
        /// </summary>
        public static string Invoicing {
            get {
                return ResourceManager.GetString("Invoicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الفواتير.
        /// </summary>
        public static string InvoicingPolicy {
            get {
                return ResourceManager.GetString("InvoicingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق إنترنت الأشياء.
        /// </summary>
        public static string IoTBox {
            get {
                return ResourceManager.GetString("IoTBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محذوف.
        /// </summary>
        public static string isDeleted {
            get {
                return ResourceManager.GetString("isDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرة حدث.
        /// </summary>
        public static string IsEventTicket {
            get {
                return ResourceManager.GetString("IsEventTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطعم.
        /// </summary>
        public static string IsRestaurant {
            get {
                return ResourceManager.GetString("IsRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أشرطة التمرير الكبيرة.
        /// </summary>
        public static string LargeScrollbars {
            get {
                return ResourceManager.GetString("LargeScrollbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر تاريخ تعديل.
        /// </summary>
        public static string LastModificationDate {
            get {
                return ResourceManager.GetString("LastModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر تاريخ تعديل.
        /// </summary>
        public static string LastModifiedDate {
            get {
                return ResourceManager.GetString("LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول للموظفين.
        /// </summary>
        public static string LoginWithEmployees {
            get {
                return ResourceManager.GetString("LoginWithEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج النقاط.
        /// </summary>
        public static string LoyaltyProgram {
            get {
                return ResourceManager.GetString("LoyaltyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم يدوي.
        /// </summary>
        public static string ManualDiscounts {
            get {
                return ResourceManager.GetString("ManualDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصنع.
        /// </summary>
        public static string Manufacture {
            get {
                return ResourceManager.GetString("Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلة التصنيع.
        /// </summary>
        public static string ManufacturingLeadTime {
            get {
                return ResourceManager.GetString("ManufacturingLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة الدفع.
        /// </summary>
        public static string MehtodName {
            get {
                return ResourceManager.GetString("MehtodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحمول.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        public static string ModfiedDate {
            get {
                return ResourceManager.GetString("ModfiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدلت بواسطة.
        /// </summary>
        public static string ModfiedUserId {
            get {
                return ResourceManager.GetString("ModfiedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدل بواسطة.
        /// </summary>
        public static string ModifiedByID {
            get {
                return ResourceManager.GetString("ModifiedByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبيعة العمل.
        /// </summary>
        public static string NaturalOfWork {
            get {
                return ResourceManager.GetString("NaturalOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية القديمة.
        /// </summary>
        public static string OldQuantity {
            get {
                return ResourceManager.GetString("OldQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على الكميات المطلوبة.
        /// </summary>
        public static string OnOrderedQuantities {
            get {
                return ResourceManager.GetString("OnOrderedQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند استلام الكميات.
        /// </summary>
        public static string OnReceivedQuantities {
            get {
                return ResourceManager.GetString("OnReceivedQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفتوح.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتج البديل.
        /// </summary>
        public static string OptionalProducts {
            get {
                return ResourceManager.GetString("OptionalProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكميات المطلوبة.
        /// </summary>
        public static string OrderedQuantities {
            get {
                return ResourceManager.GetString("OrderedQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الطلب.
        /// </summary>
        public static string OrderlineNotes {
            get {
                return ResourceManager.GetString("OrderlineNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الطلب.
        /// </summary>
        public static string OrderPrinter {
            get {
                return ResourceManager.GetString("OrderPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضرائب.
        /// </summary>
        public static string OrderTax {
            get {
                return ResourceManager.GetString("OrderTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الطلب.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المالك.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف المالك.
        /// </summary>
        public static string OwnerPhone {
            get {
                return ResourceManager.GetString("OwnerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة الرئيسية.
        /// </summary>
        public static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدفوع.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة الدفع.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرق الدفع.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد النقاط المطلوبة.
        /// </summary>
        public static string PointPerMoneySpent {
            get {
                return ResourceManager.GetString("PointPerMoneySpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفع المسبق.
        /// </summary>
        public static string PrefillCashPayment {
            get {
                return ResourceManager.GetString("PrefillCashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البادئة.
        /// </summary>
        public static string PrefixName {
            get {
                return ResourceManager.GetString("PrefixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكم في السعر.
        /// </summary>
        public static string PriceControl {
            get {
                return ResourceManager.GetString("PriceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الاسعار.
        /// </summary>
        public static string Pricelist {
            get {
                return ResourceManager.GetString("Pricelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طابعه.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان IP للطابعة.
        /// </summary>
        public static string PrinterIPAddress {
            get {
                return ResourceManager.GetString("PrinterIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطابعات.
        /// </summary>
        public static string Printers {
            get {
                return ResourceManager.GetString("Printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الطابعة.
        /// </summary>
        public static string PrinterType {
            get {
                return ResourceManager.GetString("PrinterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحصيل.
        /// </summary>
        public static string Procurement {
            get {
                return ResourceManager.GetString("Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتج.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة المنتج.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم المنتج.
        /// </summary>
        public static string ProductDiscount {
            get {
                return ResourceManager.GetString("ProductDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المنتج.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسعار المنتجات.
        /// </summary>
        public static string ProductPrices {
            get {
                return ResourceManager.GetString("ProductPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المنتج.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقتراح دعوة لتقديم العطاءات.
        /// </summary>
        public static string ProposeACallForTenders {
            get {
                return ResourceManager.GetString("ProposeACallForTenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان IP للوكيل.
        /// </summary>
        public static string ProxyIPAddress {
            get {
                return ResourceManager.GetString("ProxyIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الشراء.
        /// </summary>
        public static string PurchaseDescription {
            get {
                return ResourceManager.GetString("PurchaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة مشتريات.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتجع.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الايصال.
        /// </summary>
        public static string ReprintReceipt {
            get {
                return ResourceManager.GetString("ReprintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقيد الفئات المتاحه.
        /// </summary>
        public static string RestrictAvailableCategories {
            get {
                return ResourceManager.GetString("RestrictAvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف المبيعات.
        /// </summary>
        public static string SalesDescription {
            get {
                return ResourceManager.GetString("SalesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع.
        /// </summary>
        public static string SalesPrice {
            get {
                return ResourceManager.GetString("SalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاعد.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسلسل.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجلسة.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجلسة.
        /// </summary>
        public static string SessionNo {
            get {
                return ResourceManager.GetString("SessionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين فئة البداية.
        /// </summary>
        public static string SetStartCategory {
            get {
                return ResourceManager.GetString("SetStartCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتجر.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المتجر مطلوب.
        /// </summary>
        public static string ShopRequired {
            get {
                return ResourceManager.GetString("ShopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقف المالي المحدد.
        /// </summary>
        public static string SpecificFiscalPosition {
            get {
                return ResourceManager.GetString("SpecificFiscalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة البدء.
        /// </summary>
        public static string StartCategory {
            get {
                return ResourceManager.GetString("StartCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج قابل للتخزين.
        /// </summary>
        public static string StorableProduct {
            get {
                return ResourceManager.GetString("StorableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج الاشتراك.
        /// </summary>
        public static string SubscriptionProduct {
            get {
                return ResourceManager.GetString("SubscriptionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المورد.
        /// </summary>
        public static string SupplierImage {
            get {
                return ResourceManager.GetString("SupplierImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد مطلوب.
        /// </summary>
        public static string SupplierRequired {
            get {
                return ResourceManager.GetString("SupplierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المورد.
        /// </summary>
        public static string SupplierType {
            get {
                return ResourceManager.GetString("SupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الطاولات.
        /// </summary>
        public static string TableManagement {
            get {
                return ResourceManager.GetString("TableManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الطاولة.
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلامات.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضرائب.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر غير شامل.
        /// </summary>
        public static string TaxExcludedPrice {
            get {
                return ResourceManager.GetString("TaxExcludedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الضريبة.
        /// </summary>
        public static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر شامل الضريبة.
        /// </summary>
        public static string TaxIncludedPrice {
            get {
                return ResourceManager.GetString("TaxIncludedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضريبة على المنتج.
        /// </summary>
        public static string TaxOnProduct {
            get {
                return ResourceManager.GetString("TaxOnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضريبة المطبقة.
        /// </summary>
        public static string TaxToApply {
            get {
                return ResourceManager.GetString("TaxToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات المرشحه.
        /// </summary>
        public static string TipProduct {
            get {
                return ResourceManager.GetString("TipProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترشيح.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللقب الوظيفى.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المنتجات الكلى.
        /// </summary>
        public static string TotalItemCount {
            get {
                return ResourceManager.GetString("TotalItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن بالمقياس.
        /// </summary>
        public static string ToWeighWithScale {
            get {
                return ResourceManager.GetString("ToWeighWithScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صوره المستخدم.
        /// </summary>
        public static string UserImage {
            get {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبة القيمة المضافة مطلوبة.
        /// </summary>
        public static string VATRequired {
            get {
                return ResourceManager.GetString("VATRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة مفاتيح افتراضية.
        /// </summary>
        public static string VirtualKeyBoard {
            get {
                return ResourceManager.GetString("VirtualKeyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الالكترونى.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
