//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.Client.Pages.Resource.Shops {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddShop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddShop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointOfSale.Client.Pages.Resource.Shops.AddShop", typeof(AddShop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة متجر.
        /// </summary>
        public static string AddShops {
            get {
                return ResourceManager.GetString("AddShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكم المتقدم في النقد.
        /// </summary>
        public static string AdvancedCashControl {
            get {
                return ResourceManager.GetString("AdvancedCashControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الفاتورة.
        /// </summary>
        public static string BillPrinting {
            get {
                return ResourceManager.GetString("BillPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقسيم الفاتورة.
        /// </summary>
        public static string BillSpliitting {
            get {
                return ResourceManager.GetString("BillSpliitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفواتير والإيصالات.
        /// </summary>
        public static string BillsReceipts {
            get {
                return ResourceManager.GetString("BillsReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجهزة الموصلة.
        /// </summary>
        public static string ConnectedDevices {
            get {
                return ResourceManager.GetString("ConnectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل تفاصيل المتجر.
        /// </summary>
        public static string EnterShopDetailsAndSubmit {
            get {
                return ResourceManager.GetString("EnterShopDetailsAndSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقف المالي.
        /// </summary>
        public static string FiscalPosition {
            get {
                return ResourceManager.GetString("FiscalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجهزة والوجهة.
        /// </summary>
        public static string IntefaceDevices {
            get {
                return ResourceManager.GetString("IntefaceDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطعم.
        /// </summary>
        public static string IsABarRestaurant {
            get {
                return ResourceManager.GetString("IsABarRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظفين.
        /// </summary>
        public static string LoginWithEmployees {
            get {
                return ResourceManager.GetString("LoginWithEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالى.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوعات.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسعير والدفع.
        /// </summary>
        public static string PricingPayment {
            get {
                return ResourceManager.GetString("PricingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المتجر.
        /// </summary>
        public static string ShopDetails {
            get {
                return ResourceManager.GetString("ShopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة البدأ.
        /// </summary>
        public static string StartCategory {
            get {
                return ResourceManager.GetString("StartCategory", resourceCulture);
            }
        }
    }
}
