//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.Client.Pages.Resource.Sessions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointOfSale.Client.Pages.Resource.Sessions.SessionContent", typeof(SessionContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار صنف.
        /// </summary>
        public static string ChooseOneProduct {
            get {
                return ResourceManager.GetString("ChooseOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار عميل.
        /// </summary>
        public static string CustomerIsRequired {
            get {
                return ResourceManager.GetString("CustomerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الباركود او اسم الصنف.
        /// </summary>
        public static string EnterBarcodeOrProductName {
            get {
                return ResourceManager.GetString("EnterBarcodeOrProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق الفاتوره.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضرائب.
        /// </summary>
        public static string OrderTax {
            get {
                return ResourceManager.GetString("OrderTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفع.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الفاتورة.
        /// </summary>
        public static string PrintBill {
            get {
                return ResourceManager.GetString("PrintBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الطلب.
        /// </summary>
        public static string PrintOrder {
            get {
                return ResourceManager.GetString("PrintOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصنف.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكميه.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجمالى.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجمالى.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجمالى الاصناف.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي المدفوعات.
        /// </summary>
        public static string TotalPayable {
            get {
                return ResourceManager.GetString("TotalPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عميل غير معروف.
        /// </summary>
        public static string WalkInClient {
            get {
                return ResourceManager.GetString("WalkInClient", resourceCulture);
            }
        }
    }
}
